CREATE TABLE IF NOT EXISTS products_normalized (
  id CHAR(36) NOT NULL,
  source_system VARCHAR(32) NOT NULL DEFAULT 'PROSCAI',
  source_country_code CHAR(2) NOT NULL DEFAULT '01',
  source_icod VARCHAR(64) NOT NULL,
  source_ean VARCHAR(128) NOT NULL,

  source_description1 TEXT NULL,
  source_description2 TEXT NULL,
  source_description TEXT NULL,

  raw_fam2 VARCHAR(255) NULL,
  raw_fam3 VARCHAR(255) NULL,
  raw_fam4 VARCHAR(255) NULL,
  raw_fam5 VARCHAR(255) NULL,
  raw_fam7 VARCHAR(255) NULL,
  raw_fam8 VARCHAR(255) NULL,
  raw_famc VARCHAR(255) NULL,
  raw_unidad VARCHAR(100) NULL,

  detection_bucket VARCHAR(32) NOT NULL,
  detection_source VARCHAR(32) NOT NULL,
  detection_first_word VARCHAR(100) NULL,
  detection_first_word_product VARCHAR(100) NULL,
  detection_confidence DECIMAL(5,2) NULL,
  detection_notes TEXT NULL,

  normalized_product VARCHAR(120) NOT NULL,
  normalized_category VARCHAR(120) NULL,
  normalized_subcategory VARCHAR(120) NULL,
  normalized_material VARCHAR(120) NULL,
  normalized_tipo VARCHAR(120) NULL,
  normalized_subtipo VARCHAR(120) NULL,
  normalized_diameter VARCHAR(120) NULL,
  normalized_ced VARCHAR(120) NULL,
  normalized_costura VARCHAR(120) NULL,
  normalized_termino VARCHAR(120) NULL,
  normalized_acabado VARCHAR(120) NULL,
  normalized_radio VARCHAR(120) NULL,
  normalized_angulo VARCHAR(120) NULL,
  normalized_presion VARCHAR(120) NULL,
  normalized_grado VARCHAR(120) NULL,
  normalized_figura VARCHAR(120) NULL,

  display_name VARCHAR(255) NULL,
  display_description TEXT NULL,
  search_text LONGTEXT NULL,

  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_searchable TINYINT(1) NOT NULL DEFAULT 1,
  requires_manual_review TINYINT(1) NOT NULL DEFAULT 0,
  manual_review_reason VARCHAR(255) NULL,

  pinecone_namespace VARCHAR(64) NULL,
  pinecone_vector_id VARCHAR(128) NULL,
  pinecone_last_upsert_at DATETIME NULL,

  erp_last_seen_at DATETIME NULL,
  normalized_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_products_normalized_source (source_system, source_ean),
  KEY idx_products_normalized_ean (source_ean),
  KEY idx_products_normalized_source_icod (source_icod),
  KEY idx_products_normalized_bucket (detection_bucket),
  KEY idx_products_normalized_product (normalized_product),
  KEY idx_products_normalized_category (normalized_category, normalized_subcategory),
  KEY idx_products_normalized_material (normalized_material),
  KEY idx_products_normalized_diameter (normalized_diameter),
  KEY idx_products_normalized_active (is_active, is_searchable),
  KEY idx_products_normalized_review (requires_manual_review),
  KEY idx_products_normalized_pinecone (pinecone_vector_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
